resources:
  repositories:
    - repository: templates
      type: github
      name: ExtendRealityLtd/DevOps
      ref: refs/tags/v3.12.1
      endpoint: ExtendRealityLtd

variables:
  - group: Build
  - group: Publish

jobs:
- template: templates/jobs/cd.yml@templates
